spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ynnk?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
#  transaction:
#    rollback-on-commit-failure: true
#  activiti:
#    check-process-definitions: false
server:
  port: 8081

mybatis-plus:
  configuration:
    type-aliases-package: com.tgem.ynnk.*.entity
    mapper-locations: classpath*:mapper/*/*.xml
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  server.tomcat.uri-encoding=UTF-8
